import {useEffect, useState} from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import  Message  from '../components/message'
import {db} from '../utils/firebase'
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore'
import Link from 'next/link'



export default function Home() {

  // Create a state with all the posts
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, 'posts');
    const  q = query(collectionRef, orderBy('timestamp', 'desc'))
    // onSnapshot updates the post automatically
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({...doc.data(), id: doc.id})))
    })
     return unsubscribe;
  }

  useEffect(() => {
    getPosts();
    
  }, []);


  return (
    <div >
      <Head>
        <title>Create-blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-12 text-lg font-medium">
        <h2 className="text-1xl">See what other people are saying</h2>
        {allPosts.map((post) => (
        <Message {...post} key={post.id}>
          <Link href={{pathname: `/${post.id}`, query: {...post} }}>
              <button>{post.comments?.length} comments</button>
          </Link>
        </Message>
        ))} 
      </div>
    </div>
  );
}
